  
  ;#-------------------------------------------------ß
  ;|          x64lab  MPL 2.0 License                |
  ;|   Copyright (c) 2009-2012, Marc Rainer Kranz.   |
  ;|            All rights reserved.                 |
  ;ö-------------------------------------------------ä

  ;#-------------------------------------------------ß
  ;| uft-8 encoded üäöß
  ;| update:
  ;| filename:
  ;ö-------------------------------------------------ä


	g:
	.hDefCurs	dq 0
	.hNSCurs	dq 0
	.hWECurs		dq 0
	.hPattern	dq 0
	.hInst		dq 0
	.hBrush		dq 0
	;.hGdip 		dq 0
	;.gdipsi 	GDIPLUS_STARTUPINPUT 1,NULL, FALSE, FALSE

	.pt				POINT
	.cx_sframe		dw 0
	.cy_sframe		dw 0
	.cy_caption		dw 0
	.cy_border		dw 0
	.cx_smicon		dw 0
	.cy_smicon		dw 0
	.cx_smsize		dw 0
	.cy_smsize		dw 0
