  
  ;#-------------------------------------------------ß
  ;|          x64lab  MPL 2.0 License                |
  ;|   Copyright (c) 2009-2012, Marc Rainer Kranz.   |
  ;|            All rights reserved.                 |
  ;ö-------------------------------------------------ä

  ;#-------------------------------------------------ß
  ;| uft-8 encoded üäöß
  ;| update:
  ;| filename:
  ;ö-------------------------------------------------ä


import UXTHEME,\
       BeginBufferedAnimation,'BeginBufferedAnimation',\
       BeginBufferedPaint,'BeginBufferedPaint',\
       BeginPanningFeedback,'BeginPanningFeedback',\
       BufferedPaintClear,'BufferedPaintClear',\
       BufferedPaintInit,'BufferedPaintInit',\
       BufferedPaintRenderAnimation,'BufferedPaintRenderAnimation',\
       BufferedPaintSetAlpha,'BufferedPaintSetAlpha',\
       BufferedPaintStopAllAnimations,'BufferedPaintStopAllAnimations',\
       BufferedPaintUnInit,'BufferedPaintUnInit',\
       CloseThemeData,'CloseThemeData',\
       DrawThemeBackground,'DrawThemeBackground',\
       DrawThemeBackgroundEx,'DrawThemeBackgroundEx',\
       DrawThemeEdge,'DrawThemeEdge',\
       DrawThemeIcon,'DrawThemeIcon',\
       DrawThemeParentBackground,'DrawThemeParentBackground',\
       DrawThemeParentBackgroundEx,'DrawThemeParentBackgroundEx',\
       DrawThemeText,'DrawThemeText',\
       DrawThemeTextEx,'DrawThemeTextEx',\
       EnableThemeDialogTexture,'EnableThemeDialogTexture',\
       EnableTheming,'EnableTheming',\
       EndBufferedAnimation,'EndBufferedAnimation',\
       EndBufferedPaint,'EndBufferedPaint',\
       EndPanningFeedback,'EndPanningFeedback',\
       GetBufferedPaintBits,'GetBufferedPaintBits',\
       GetBufferedPaintDC,'GetBufferedPaintDC',\
       GetBufferedPaintTargetDC,'GetBufferedPaintTargetDC',\
       GetBufferedPaintTargetRect,'GetBufferedPaintTargetRect',\
       GetCurrentThemeName,'GetCurrentThemeName',\
       GetThemeAppProperties,'GetThemeAppProperties',\
       GetThemeBackgroundContentRect,'GetThemeBackgroundContentRect',\
       GetThemeBackgroundExtent,'GetThemeBackgroundExtent',\
       GetThemeBackgroundRegion,'GetThemeBackgroundRegion',\
       GetThemeBitmap,'GetThemeBitmap',\
       GetThemeBool,'GetThemeBool',\
       GetThemeColor,'GetThemeColor',\
       GetThemeDocumentationProperty,'GetThemeDocumentationProperty',\
       GetThemeEnumValue,'GetThemeEnumValue',\
       GetThemeFilename,'GetThemeFilename',\
       GetThemeFont,'GetThemeFont',\
       GetThemeInt,'GetThemeInt',\
       GetThemeIntList,'GetThemeIntList',\
       GetThemeMargins,'GetThemeMargins',\
       GetThemeMetric,'GetThemeMetric',\
       GetThemePartSize,'GetThemePartSize',\
       GetThemePosition,'GetThemePosition',\
       GetThemePropertyOrigin,'GetThemePropertyOrigin',\
       GetThemeRect,'GetThemeRect',\
       GetThemeStream,'GetThemeStream',\
       GetThemeString,'GetThemeString',\
       GetThemeSysBool,'GetThemeSysBool',\
       GetThemeSysColor,'GetThemeSysColor',\
       GetThemeSysColorBrush,'GetThemeSysColorBrush',\
       GetThemeSysFont,'GetThemeSysFont',\
       GetThemeSysInt,'GetThemeSysInt',\
       GetThemeSysSize,'GetThemeSysSize',\
       GetThemeSysString,'GetThemeSysString',\
       GetThemeTextExtent,'GetThemeTextExtent',\
       GetThemeTextMetrics,'GetThemeTextMetrics',\
       GetThemeTransitionDuration,'GetThemeTransitionDuration',\
       GetWindowTheme,'GetWindowTheme',\
       HitTestThemeBackground,'HitTestThemeBackground',\
       IsAppThemed,'IsAppThemed',\
       IsCompositionActive,'IsCompositionActive',\
       IsThemeActive,'IsThemeActive',\
       IsThemeBackgroundPartiallyTransparent,'IsThemeBackgroundPartiallyTransparent',\
       IsThemeDialogTextureEnabled,'IsThemeDialogTextureEnabled',\
       IsThemePartDefined,'IsThemePartDefined',\
       OpenThemeData,'OpenThemeData',\
       OpenThemeDataEx,'OpenThemeDataEx',\
       SetThemeAppProperties,'SetThemeAppProperties',\
       SetWindowTheme,'SetWindowTheme',\
       SetWindowThemeAttribute,'SetWindowThemeAttribute',\
       ThemeInitApiHook,'ThemeInitApiHook',\
       UpdatePanningFeedback,'UpdatePanningFeedback'